[ALPS02191773] emmc: fix panic build error
[Detail] add path to support aee feature enable
build error log:
.............................
199   CC      drivers/misc/mediatek/ram_console/mtk_ram_console.o
200 In file included from ../drivers/misc/mediatek/ram_console/
mtk_ram_console.c:158:0:
201 ../drivers/misc/mediatek/include/mt-plat/sd_misc.h:13:61:
error: struct msdc_hw declared inside parameter list     [-Werror]
202  extern void msdc_set_driving(struct msdc_host *host,
struct msdc_hw *hw, bool sd_18);
203                                                              ^
204 ../drivers/misc/mediatek/include/mt-plat/sd_misc.h:13:61:
error: its scope is only this definition or declaration,
which is probably not what you want [-Werror]
205 ../drivers/misc/mediatek/include/mt-plat/sd_misc.h:13:61:
error: struct msdc_host declared inside parameter lis    t [-Werror]
206 ../drivers/misc/mediatek/include/mt-plat/sd_misc.h:15:27:
error: HOST_MAX_NUM undeclared here (not in a functio    n)
207  extern u32 msdc_host_mode[HOST_MAX_NUM];

[Solution] enable aee feature in kernel config will cause
build error,so add head file path to fix

[Feature] eMMC Boot Up

MTK-Commit-Id: 67fac66218b6f19366031a8c14e715bc5931690f

Change-Id: I9661ae8448a06811923e71627dd70b3b396bb266
CR-Id: ALPS02191773